const html = await (await fetch("https://swiftfixs.app/")).text();

for (const property of ["og:title", "og:description", "og:image", "og:url"]) {
  const match = html.match(
    new RegExp(`<meta property="${property}" content="([^"]+)"`)
  );
  console.log(`${property}:`, match?.[1] ?? "MISSING");
}

const image = await fetch("https://swiftfixs.app/og-image.png", {
  method: "HEAD",
});
console.log(
  "og-image:",
  image.status,
  image.headers.get("content-type"),
  image.headers.get("content-length")
);

console.log(
  "stale metadata:",
  /Create Next App|Generated by create next app/i.test(html)
);
