#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# If package-lock.json changed in the merge, refresh deps automatically.
if git diff --name-only ORIG_HEAD HEAD | grep -q "^package-lock\\.json$"; then
  npm install
fi
